#########
# PROJECT
#########

# Certain tasks may operate in a less secure (but more convenient) manner, eg.
# enabling passwordless sudo or generating self-signed ssl certs, when testing
# locally, in Vagrant. But not in production!
env: development

# This var is referenced by a few other vars, eg. git_repo, hostname, site_fqdn.
project_name: bocoup-wpengine

# Vagrant box hostname and FQDN. The site_fqdn setting should match the vagrant
# inventory ansible_ssh_host and Vagrantfile config.hostsupdater.aliases
# settings.
hostname: bocoup-wpengine-vagrant
site_fqdn: "{{project_name}}.loc"

# Location under which all WordPress files will be installed.
base_path: /mnt

# Vagrant box synced folder. This should match the config.vm.synced_folder
# setting in the Vagrantfile, and should be different than the public_dir var.
synced_folder: "{{base_path}}/vagrant"

##############
# PROVISIONING
##############

# Keys to be used by Apt.
apt_keys:
  - "https://deb.nodesource.com/gpgkey/nodesource.gpg.key"

# Ppas to be added to Apt.
apt_ppas:
  - "ppa:git-core/ppa"

# Any Apt packages to install. Apt package versions may be specified like
# - git=2.1.0
apt_packages:
  - nginx
  - git
  - mysql-server
  - python-mysqldb
  - memcached
  - php5
  - php5-fpm
  - php5-mysql
  - php5-memcached
  - php5-gd
  - libssh2-php
  - postfix
  - ca-certificates
  - mailutils

############
# WEB SERVER
############

# Should the nginx server use HTTPS instead of HTTP?
ssl: false

# If ssl is enabled, these cert/key files will be used by nginx. Self-signed
# cert/key files will be auto-generated if they don't already exist.
ssl_cert_path: /etc/ssl/server.cert
ssl_key_path: /etc/ssl/server.key

# Use a custom parameter for stronger DHE key exchange.
dhe_param_path: /etc/ssl/certs/dhparam.pem

# Nginx dir and conf dir.
nginx_dir: /etc/nginx
conf_dir: "{{nginx_dir}}/conf.d"

# Nginx templated configuration files to create.
shared:
  - {file: ssl_params, directory: "{{nginx_dir}}"}
  - {file: gzip_params, directory: "{{nginx_dir}}"}
confs:
  - {file: site.conf, directory: "{{conf_dir}}"}

######
# SMTP
######

postfix_relayhost: "[smtp.gmail.com]:587"
postfix_smtp_sasl_user: bocoup.test@gmail.com
postfix_smtp_sasl_password: $ecurePa$$w0rd

postfix_smtpd_use_tls: yes
postfix_myhostname: "{{inventory_hostname}}"
postfix_myorigin: $myhostname
postfix_smtp_sasl_auth_enable: yes
postfix_smtp_tls_cafile: /etc/ssl/certs/Thawte_Premium_Server_CA.pem
postfix_mynetworks: "127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128"
postfix_inet_interfaces: loopback-only
postfix_mydestination: $mydomain, $myhostname, localhost.$mydomain, localhost
postfix_local_recipient_map: ""

postfix_generic_maps: ""

# Relay all mail going to local users (e.g. root or cron) to another mail address
postfix_local_user_relay_address: ""

# Useful if you use a SMTP server for relay that doesn't allow
# arbitrary sender addresses.
postfix_rewrite_sender_address: ""

# Send a test mail to this address when Postfix configuration changes
postfix_send_test_mail_to: "{{postfix_smtp_sasl_user}}"

# Queue
bounce_queue_lifetime: 1h
maximal_queue_lifetime: 1h
maximal_backoff_time: 15m
minimal_backoff_time: 5m
queue_run_delay: 5m

###########
# WORDPRESS
###########

# Version and checksum of the WordPress download archive. From this page:
# https://wordpress.org/download/release-archive/
wp_version: 4.3.1
wp_version_md5: de8004fa1035817435eaa780a681aaff

# Database configuration.
wp_db_name: wordpress
wp_db_password: test123
wp_db_user: root
wp_db_host: localhost
wp_db_table_prefix: wp_

wp_user: www-data
wp_group: www-data
wp_install_dir: "{{base_path}}/wordpress-{{wp_version}}"
public_dir: "{{base_path}}/www"

# The location of the theme.
theme_path: "{{base_path}}/www/wp-content/themes/underscores/"

# Enable debugging in WordPress.
wp_debug: true

# Salts and keys. Change these to invalidate all existing cookies.
# https://api.wordpress.org/secret-key/1.1/salt/
wp_salts_keys: |
  define('AUTH_KEY',         '9A:]N4R |*C}i6oOH%I}@O1AREW)i#UE8=v;y:*ep38;Y72hVROypA&4n{v`k=Bn');
  define('SECURE_AUTH_KEY',  'qbhlf3r6nBSR7q8OFxl@kW7!Y+Jjl+k.J`/6+>WT>>8En?])QU,U+l#v5W#YUNt0');
  define('LOGGED_IN_KEY',    '& !V(:m<=|KeX@magB9&+A-Twv5.%)A2[Eb0%+-X(ybhd9:3p= :?l-aaI+ulAQA');
  define('NONCE_KEY',        'OD]ac f:%ir}+p+?SBhV0c,*!Zu|!s$gnSV:z!;?t!#/#xa)-0KB6}+_s_~94;vs');
  define('AUTH_SALT',        'F7U%1Q5V1xL`nQhhz[NO|*M|{4K.K0`Nyar(CsX]jFE%}:((1:!A]SNXPB4^nu+|');
  define('SECURE_AUTH_SALT', ')9rE&rX_(UICv;NJ(.r]F n#48J|t266*7ZHya9:n~E V@+<GV4CB(;Os^yPc.yL');
  define('LOGGED_IN_SALT',   '4f!C~;o%v^1S0/%XBJA27s%*lF(FAv}RAnb5d+umW^2vhkK>lLuMK{7~MX>GNoVq');
  define('NONCE_SALT',       'J|1(3;*1~&;84(VMg@#9-s+0Ix?U6.2220cdW[BN1V[0(3$!D2F+!YbXoqMNM=AC');

############
# EXTRA VARS
############

# wordpress role: Force install of the specified version of WordPress.
wp_force: false
